{
    "openapi": "3.0.3",
    "info": {
        "title": "To Do List RestFul API",
        "version": "1",
        "description": "openapi for To Do List RestFul API",
        "termsOfService": "https://www.facebook.com/Falldy.H/",
        "contact": {
            "name": "Faldi Harido Fihan",
            "email": "faldiharido@gmail.com",
            "url": "https://github.com/Falllll"
        },
        "license": {
            "name": "APACHE 2.0",
            "url": "https://www.apache.org/licenses/LICENSE-2.0"
        }
    },
    "servers": [{
        "description": "To Do List RestFul API server",
        "url": "https://localhost:8000/{env}",
        "variables": {
            "env": {
                "description": "server environment",
                "default": "dev",
                "enum": [
                    "dev",
                    "qa",
                    "prod"
                ]
            }
        }
    }],
    "externalDocs": {
        "description": "Link github",
        "url": "https://github.com/falllll"
    },
    "paths": {
        "/to-do-list": {
            "get": {
                "tags": ["Todolist"],
                "summary": "Get All Todolist",
                "description": "Only will return active todolist, complete todolist or deleted todolist will be removed",
                "parameters": [{
                        "name": "include_done",
                        "in": "query",
                        "required": false,
                        "description": "Is include done To Do List",
                        "schema": {
                            "type": "boolean",
                            "nullable": true,
                            "default": false
                        }
                    },
                    {
                        "name": "name",
                        "in": "query",
                        "required": false,
                        "description": "Filter To DO List by name",
                        "schema": {
                            "type": "string",
                            "nullable": true,
                            "minLength": 1,
                            "maxLength": 100
                        },
                        "examples": {
                            "java": {
                                "description": "Example Java",
                                "value": "Java"
                            },
                            "php": {
                                "description": "Example PHP",
                                "value": "PHP"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success get all to do list",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "id": {
                                                "type": "string"
                                            },
                                            "name": {
                                                "type": "string"
                                            },
                                            "priority": {
                                                "type": "number",
                                                "format": "int32"
                                            },
                                            "tags": {
                                                "type": "array",
                                                "items": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                },
                                "examples": {
                                    "Success": {
                                        "description": "Example Success get all to do list",
                                        "value": [{
                                                "id": "1",
                                                "name": "Java",
                                                "priority": 3,
                                                "tags": [
                                                    "Java", "Programming"
                                                ]
                                            },
                                            {
                                                "id": "2",
                                                "name": "PHP",
                                                "priority": 5,
                                                "tags": [
                                                    "PHP", "Programming"
                                                ]
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "tags": ["Todolist"],
                "summary": "Create new Todolist",
                "description": "Create new active todolist",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "name": {
                                        "type": "string",
                                        "minLength": 1,
                                        "required": true
                                    },
                                    "priority": {
                                        "type": "integer",
                                        "format": "int32",
                                        "default": 1,
                                        "required": true
                                    },
                                    "tags": {
                                        "type": "array",
                                        "required": false,
                                        "minItems": 1,
                                        "items": {
                                            "type": "string",
                                            "minLength": 1
                                        }
                                    }
                                }
                            },
                            "examples": {
                                "java": {
                                    "description": "Example Java",
                                    "value": {
                                        "name": "Java",
                                        "priority": 3,
                                        "tags": [
                                            "Java", "Programming"
                                        ]
                                    }
                                },
                                "php": {
                                    "description": "Example PHP",
                                    "value": {
                                        "name": "PHP",
                                        "priority": 5,
                                        "tags": [
                                            "PHP", "Programming"
                                        ]
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success Create todolist",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "id": {
                                            "type": "string"
                                        },
                                        "name": {
                                            "type": "string"
                                        },
                                        "priority": {
                                            "type": "number",
                                            "format": "int32"
                                        },
                                        "tags": {
                                            "type": "array",
                                            "items": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                },
                                "examples": {
                                    "java": {
                                        "description": "Success Create Java todolist",
                                        "value": {
                                            "id": "1",
                                            "name": "Java",
                                            "priority": 3,
                                            "tags": [
                                                "Java", "Programming"
                                            ]
                                        }
                                    },
                                    "php": {
                                        "description": "Success Create PHP todolist",
                                        "value": {
                                            "id": "1",
                                            "name": "PHP",
                                            "priority": 3,
                                            "tags": [
                                                "PHP", "Programming"
                                            ]
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/to-do-list/{todolistId}": {
            "put": {
                "tags": ["Todolist"],
                "summary": "Update existing todolist",
                "description": "Update todolist",
                "parameters": [{
                    "name": "todolistId",
                    "in": "path",
                    "required": true,
                    "description": "To do List updated",
                    "schema": {
                        "type": "string",
                        "minLength": 1,
                        "maxLength": 100
                    },
                    "examples": {
                        "java": {
                            "description": "Sample id for Java",
                            "value": "1"
                        },
                        "php": {
                            "description": "Sample id for PHP",
                            "value": "2"
                        }
                    }
                }],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "name": {
                                        "type": "string",
                                        "minLength": 1,
                                        "required": true
                                    },
                                    "priority": {
                                        "type": "integer",
                                        "format": "int32",
                                        "default": 1,
                                        "required": true
                                    },
                                    "tags": {
                                        "type": "array",
                                        "required": false,
                                        "minItems": 1,
                                        "items": {
                                            "type": "string",
                                            "minLength": 1
                                        }
                                    }
                                }
                            },
                            "examples": {
                                "java": {
                                    "description": "Example Java",
                                    "value": {
                                        "name": "Java",
                                        "priority": 3,
                                        "tags": [
                                            "Java", "Programming"
                                        ]
                                    }
                                },
                                "php": {
                                    "description": "Example PHP",
                                    "value": {
                                        "name": "PHP",
                                        "priority": 5,
                                        "tags": [
                                            "PHP", "Programming"
                                        ]
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success Update todolist",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "id": {
                                            "type": "string"
                                        },
                                        "name": {
                                            "type": "string"
                                        },
                                        "priority": {
                                            "type": "number",
                                            "format": "int32"
                                        },
                                        "tags": {
                                            "type": "array",
                                            "items": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                },
                                "examples": {
                                    "java": {
                                        "description": "Success Update Java todolist",
                                        "value": {
                                            "id": "1",
                                            "name": "Java",
                                            "priority": 3,
                                            "tags": [
                                                "Java", "Programming"
                                            ]
                                        }
                                    },
                                    "php": {
                                        "description": "Success Update PHP todolist",
                                        "value": {
                                            "id": "1",
                                            "name": "PHP",
                                            "priority": 3,
                                            "tags": [
                                                "PHP", "Programming"
                                            ]
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "tags": ["Todolist"],
                "summary": "Delete todolist",
                "description": "Delete todolist",
                "parameters": [{
                    "name": "todolistId",
                    "in": "path",
                    "required": true,
                    "description": "To Do List Deleted",
                    "schema": {
                        "type": "string",
                        "minLength": 1,
                        "maxLength": 100
                    }
                }],
                "responses": {
                    "200": {
                        "description": "Success Delete todolist",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "success": {
                                            "type": "boolean"
                                        }
                                    }
                                },
                                "examples": {
                                    "success": {
                                        "description": "Success delete todolist",
                                        "value": {
                                            "success": true
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Failed Delete todolist",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "success": {
                                            "type": "boolean"
                                        }
                                    }
                                },
                                "examples": {
                                    "failed": {
                                        "description": "Success delete todolist",
                                        "value": {
                                            "failed": false
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "parameters": {
            "name": "todolistId",
            "in": "path",
            "required": true,
            "description": "To do List updated",
            "schema": {
                "type": "string",
                "minLength": 1,
                "maxLength": 100
            },
            "examples": {
                "java": {
                    "description": "Sample id for Java",
                    "value": "1"
                },
                "php": {
                    "description": "Sample id for PHP",
                    "value": "2"
                }
            }
        },
        "schemas": {
            "TodoList": {
                "type": "object",
                "properties": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "string"
                        },
                        "name": {
                            "type": "string"
                        },
                        "priority": {
                            "type": "number",
                            "format": "int32"
                        },
                        "tags": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "CreateOrUpdateTodoList": {
                "type": "object",
                "properties": {
                    "type": "object",
                    "properties": {
                        "name": {
                            "type": "string"
                        },
                        "priority": {
                            "type": "number",
                            "format": "int32"
                        },
                        "tags": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "ArrayTodoList": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "string"
                        },
                        "name": {
                            "type": "string"
                        },
                        "priority": {
                            "type": "number",
                            "format": "int32"
                        },
                        "tags": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    }
}